import './globals.css'
import {Roboto} from 'next/font/google'
import Header from "@/app/components/Header";
import Footer from "@/app/components/Footer";



const mulish = Roboto({
    weight: ['300','400','500','600','700','800','900','1000'],
    subsets: ['latin'],
    display: 'swap'
})
export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body>
      <Header />
      {children}
      <Footer/>
      </body>
    </html>
  )
}
